#!/bin/bash

function mpa_to_ascii
{
   ADC=8
   while [ $ADC -ge 0 ]; do
      if grep -q DATA$((ADC-1)) $filename ; then
         newfilename=$(echo $filename | sed "s/\.mpa/\_$ADC\.tv/")
	 sed "1,/DATA$((ADC-1))/d" $filename > $newfilename
	 sed -i "/DATA/q" $newfilename
	 sed -i "/DATA/d" $newfilename
	 fi
	 ADC=$((ADC-1))
   done
}

if test $1 ; then
   while [ "$1" != "" ]; do
      if [ -f $1 ] ; then
	    filename=$1
	    $(mpa_to_ascii)
	 else
	    echo -e "\a!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	    echo -e "File $1 doesn't exist"
	    echo -e "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	 fi
	 shift
   done
elif ls *.mpa ; then
   echo -e "\a!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
   echo -e "Converting all mpa files in the directory"
   echo -e "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
   for filename in *.mpa ; do
      $(mpa_to_ascii)
   done
else
   echo -e "\a!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
   echo -e "There are no mpa files in the directory"
   echo -e "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

fi
   
exit 0
