#!/bin/bash

function spe_to_ascii
{
   newfilename=$(echo $filename | sed "s/\.Spe/\.tv/")
   sed "1,/0\ 4095/d" $filename > $newfilename
#   sed -i "/DATA/q" $newfilename
   sed -i "/ROI/,\$d" $newfilename
}

if test $1 ; then
   while [ "$1" != "" ]; do
      if [ -f $1 ] ; then
	    filename=$1
	    $(spe_to_ascii)
	 else
	    echo -e "\a!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	    echo -e "File $1 doesn't exist"
	    echo -e "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	 fi
	 shift
   done
elif ls *.Spe ; then
   echo -e "\a!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
   echo -e "Converting all Spe files in the directory"
   echo -e "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
   for filename in *.Spe ; do
      $(spe_to_ascii)
   done
else
   echo -e "\a!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
   echo -e "There are no Spe files in the directory"
   echo -e "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

fi
   
exit 0
