#!/bin/bash

function stut_to_ascii
{
   sed '1,/SpectrumText/ d' < $filename > $filename.tv
   grep ROI $filename > dumpfile12345
   v1=`wc -l dumpfile12345 | awk '{print $1}' `
   rm -f dumpfile12345
   sed -i '1,/'$v1'/ d' $filename.tv
   sed -i {s/','/'\n'/g} $filename.tv
}

if test $1 ; then
   while [ "$1" != "" ]; do
      if [ -f $1 ] ; then
	    filename=$1
	    $(stut_to_ascii)
	 else
	    echo -e "\a!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	    echo -e "  File $1 doesn't exist"
	    echo -e "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	 fi
	 shift
   done
elif ls D[0-9]*.[0-9]* ; then
   echo -e "\a!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
   echo -e "  Converting all files in the directory  "
   echo -e "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
   for filename in D[0-9]*.[0-9]* ; do
      $(stut_to_ascii)
   done
else
   echo -e "\a!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
   echo -e "  There are no files in the directory  "
   echo -e "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

fi
   
exit 0
